---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Template Wordpress. Web - 1 instance EC2 t2.micro (ubuntu, apache, wp), DB - RDS (MySQL).

Parameters:
  VpcId:
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    Type: 'AWS::EC2::VPC::Id'
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  #Subnets:
  #  Type: List<AWS::EC2::Subnet::Id>
  #  Description: subnets
  #  ConstraintDescription: subnets
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: learn-aws-wp.pem
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  DBClass:
    Default: db.t2.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: 5
    Description: The size of the database (Gb)
    Type: Number
    MinValue: 5
    MaxValue: 20
    ConstraintDescription: must be between 5 and 1024Gb.
  DBName:
    Default: wordpressdb
    Description: The WordPress database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: The WordPress database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t2.micro:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-04169656fea786776

Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: wp1
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
      VpcId:
        Ref: "VpcId"

  DBSecurityGroup:
    Type: 'AWS::RDS::DBSecurityGroup'
    Properties:
      GroupDescription: "Open database for access"
      DBSecurityGroupIngress:
        -
          EC2SecurityGroupId:
            Ref: "WebServerSecurityGroup"
      EC2VpcId:
        Ref: "VpcId"

  #DBSubnetGroup:
  #  Type: AWS::RDS::DBSubnetGroup
  #  Properties:
  #    DBSubnetGroupDescription: subnets
  #    SubnetIds:
  #      Ref: Subnets
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - S3FullAccess 
  
  WebServer:
    Type: 'AWS::EC2::Instance'
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
          - apache
          - config-cfn-hup
          - wordpress
        apache:
          packages:
            apt:
              apache2: []
              php: []
              php-mysql: []
              libapache2-mod-php: []
          commands:
            rm_index_html:
              command: "rm /var/www/html/index.html"
        config-cfn-hup:
          files:
            '/etc/cfn/cfn-hup.conf':
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
            '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServer.Metadata.AWS::CloudFormation::Init
                action=/usr/local/bin/cfn-init -v --stack ${AWS::StackId} --resource WebServer --region ${AWS::Region}
                runas=root
            '/etc/systemd/system/cfn-hup.service':
              content: !Sub |
                [Unit]
                Description=Cloud formation helper daemon
                [Service]
                ExecStart=/usr/local/bin/cfn-hup
                Restart=always
                Type=simple
                [Install]
                WantedBy=multi-user.target
          commands: 
            enable-cfn-hup:
              command: "systemctl enable cfn-hup.service" 
            start-cfn-hup:
              command: "systemctl start cfn-hup.service"
        wordpress:
          source:
            /var/www/html: !Sub "https://s3-eu-west-1.amazonaws.com/cf-templates-19ycoujyu7ety-us-east-1/LATEST_BUILD"
              
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: !Sub |
            #!/bin/bash -xe
            apt-get update
            apt-get -y install python-pip
            export LC_ALL=C
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            /usr/local/bin/cfn-init -v --stack ${AWS::StackId} --resource WebServer --region ${AWS::Region}
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WebServer --region ${AWS::Region}

          #  sudo service apache2 restart
          #  sudo rm /var/www/html/index.html
          #  cd /tmp/
          #  wget https://wordpress.org/latest.tar.gz
          #  sudo tar -xzvf latest.tar.gz -C /var/www/html/
          #  sudo mv -f /var/www/html/wordpress/* /var/www/html/
          #  sudo mv -f /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          #  sudo sed -i "s/localhost/${DBAddress}/g" /var/www/html/wp-config.php
          #  sudo sed -i "s/username_here/${DBUser}/g" /var/www/html/wp-config.php
          #  sudo sed -i "s/password_here/${DBPassword}/g" /var/www/html/wp-config.php
          #  sudo sed -i "s/database_name_here/${DBName}/g" /var/www/html/wp-config.php
          #  sudo service apache2 restart
          #- {
          #  DBAddress: !GetAtt DBInstance.Endpoint.Address,
          #  DBPassword: !Ref DBPassword,
          #  DBUser: !Ref DBUser,
          #  DBName: !Ref DBName
          #  }

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage:
        Ref: DBAllocatedStorage
      BackupRetentionPeriod: 0
      DBName:
        Ref: DBName
      #DBSubnetGroupName:
      #  Ref: DBSubnetGroup
      DBInstanceClass:
        Ref: DBClass
      DBSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: wpdb
      Engine: MySQL
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
Outputs:
  InstanceAddress:
    Description: The Instance Public IP Address
    Value: !GetAtt WebServer.PublicIp
